calculator/urls.py
from django.urls import path

from . import views

from django.conf.urls import url
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.conf.urls import include
app_name = 'calculate'
urlpatterns = [
    path('', views.home, name='home'),
    path('about',views.about,name='about'),
]

calculator_get/urls.py
from django.urls import path

from . import views

from django.conf.urls import url
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.conf.urls import include
app_name = 'calculate_get'
urlpatterns = [
    path('get', views.home, name='home'),
]

s_6101012630160/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calculator.urls')),
    path('', include('calculator_get.urls')),
]

calculator/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class Calculate(models.Model):
    num1 = models.IntegerField(default=0)
    num2 = models.IntegerField(default=0)
    operate = models.TextField(blank=True)
    result = models.IntegerField(default=0)
    def calculate(self,int1,int2,operate2,result2):
        self.num1 = int1
        self.num2 = int2
        self.operate = operate2
        self.result =result2
        self.save()

calculator_get/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

class Calculate_get(models.Model):
    num1 = models.IntegerField(default=0)
    num2 = models.IntegerField(default=0)
    operate = models.TextField(blank=True)
    result = models.IntegerField(default=0)
    def calculate(self,int1,int2,operate2,result2):
        self.num1 = int1
        self.num2 = int2
        self.operate = operate2
        self.result =result2
        self.save()

calculator/views.py
from django.shortcuts import render

# Create your views here.
from calculator.models import Calculate


def calculating(num, num2, operate):
    if operate == "+":
        resultvalue = int(num) + int(num2)
    elif operate == "-":
        resultvalue = int(num) - int(num2)
    elif operate == "*":
        resultvalue = int(num) * int(num2)
    elif operate == "/":
        resultvalue = int(num) / int(num2)
    return resultvalue
def home(request):
    history_list = Calculate.objects.all()
    string_list = []
    for history in history_list:
        string_list.append(str(history.num1) + history.operate + str(history.num2) + " " +"is"+" "+":"+str(history.result))
    if request.POST.get('continue'):
        return render(request,"calculator/home.html",{"last_result":Calculate.objects.last(),"check":1,"history":string_list})
    if request.POST.get("find value"):
        num = request.POST['x']
        num2 = request.POST['y']
        operates = request.POST.getlist("operate_list")
        if num == '' or num2 == '' or operates == []:
            return render(request,"calculator/home.html",{"result_list":"plz enter your input"})
        else :
            result_list = {}
            for operate in operates:
                object = Calculate.objects.create()
                result = calculating(num,num2,operate)
                result_list[operate]=result
                object.calculate(num, num2, operate, result)

        return render(request, "calculator/home.html", {"operate": operate,'op':operates, "x": num, "y": num2,"result_list":result_list,"history":string_list})
    if request.POST.get('clear_history'):
        for history in history_list:
            history.delete()
        return render(request,"calculator/home.html",{"history":Calculate.objects.all()})
    return render(request,"calculator/home.html",{"history":string_list})
def about(request):
    name = "Watcharawut Pornsawat"
    code = 6101012630160
    return render(request,"calculator/about.html",{"name":name,"Code":code})

calculator_get/views.py
from django.shortcuts import render

# Create your views here.
from calculator_get.models import Calculate_get


def calculating(num, num2, operate):
    if operate == "+":
        resultvalue = int(num) + int(num2)
    elif operate == "-":
        resultvalue = int(num) - int(num2)
    elif operate == "*":
        resultvalue = int(num) * int(num2)
    elif operate == "/":
        resultvalue = int(num) / int(num2)
    return resultvalue
def home(request):
    history_list = Calculate_get.objects.all()
    string_list = []
    for history in history_list:
        string_list.append(str(history.num1) + history.operate + str(history.num2) + " " +"is"+" "+":"+str(history.result))
    if request.GET.get('continue'):
        return render(request,"calculator/home.html",{"last_result":Calculate_get.objects.last(),"check":1,"history":string_list})
    if request.GET.get("find value"):
        num = request.GET['x']
        num2 = request.GET['y']
        operates = request.GET.getlist("operate_list")
        if num == '' or num2 == '' or operates == []:
            return render(request,"get_templates/home.html",{"result_list":"plz enter your input"})
        else :
            result_list = {}
            for operate in operates:
                object = Calculate_get.objects.create()
                result = calculating(num,num2,operate)
                result_list[operate]=result
                object.calculate(num, num2, operate, result)

        return render(request, "get_templates/home.html", {"operate": operate,'op':operates, "x": num, "y": num2,"result_list":result_list,"history":string_list})
    if request.GET.get('clear_history'):
        for history in history_list:
            history.delete()
        return render(request,"get_templates/home.html",{"history":Calculate_get.objects.all()})
    return render(request,"get_templates/home.html",{"history":string_list})

calculator/templates/calculator/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <h1>About Me</h1>
    <p>Full name : {{ name }}</p>
    <p>student ID: {{ Code }}</p>
    <a href="{% url 'calculate:home' %}">go to post method</a>
    <a href="{% url 'calculate_get:home' %}">go to get_method</a>
</head>
<body>

</body>
</html>

calculator/templates/calculator/home.html
<!DOCTYPE html>
<html lang="en">
<h1>Calculator</h1>
<head>
    {% if check %}
    <form method="POST">
        <input name="x" id="x1" placeholder="Enter a subject" value = {{ last_result.result }} />
        <input name="y" id="y1" placeholder="Enter a subject" />
        <li><input name="operate_list" type="checkbox" value="+"><label>+</label></li>
        <li><input name="operate_list" type="checkbox" value="-"><label>-</label></li>
        <li><input name="operate_list" type="checkbox" value="*"><label>*</label></li>
        <li><input name="operate_list" type="checkbox" value="/"><label>/</label></li>
        <li><input name="find value" type="submit" value="result"></li>
        <li><input name="continue"type="submit" value="continue"></li>
        {% csrf_token %}
    </form>
       {% for key,value in result_list.items %}
        <p>the result {{ x }} {{ key }} {{ y }} is :{{ value }}</p></td>
    {% endfor %}

    <h1 name = 'history'>History</h1>
    {% for history in history %}
        <p>the result {{ history }}</p></td>
    {% endfor %}
    <form method="POST">
        <input name="clear_history" type="submit" value="Clear History">
        {% csrf_token %}
    </form>
    <a href="{% url 'calculate_get:home' %}">go to get_method</a>
    <a href="{% url 'calculate:about' %}">go to About</a>

    {% else %}
    <form method="POST">
        <input name="x" id="x" placeholder="Enter a subject" />
        <input name="y" id="y" placeholder="Enter a subject" />
        <li><input name="operate_list" type="checkbox" value="+"><label>+</label></li>
        <li><input name="operate_list" type="checkbox" value="-"><label>-</label></li>
        <li><input name="operate_list" type="checkbox" value="*"><label>*</label></li>
        <li><input name="operate_list" type="checkbox" value="/"><label>/</label></li>
        <li><input name="find value" type="submit" value="result"></li>
        <li><input name="continue"type="submit" value="continue"></li>
        {% csrf_token %}
    </form>
       {% for key,value in result_list.items %}
        <p>the result {{ x }} {{ key }} {{ y }} is :{{ value }}</p></td>
    {% endfor %}

    <h1 name = 'history'>History</h1>
    {% for history in history %}
        <p>the result {{ history }}</p></td>
    {% endfor %}
    <form method="POST">
        <input name="clear_history" type="submit" value="Clear History">
        {% csrf_token %}
    </form>
    <a href="{% url 'calculate_get:home' %}">go to get_method</a>
    <a href="{% url 'calculate:about' %}">go to About</a>
    {% endif %}
</head>
<body>

</body>
</html>

calculator_get/templates/get_templates/home.html
<!DOCTYPE html>
<html lang="en">
<h1>Calculator</h1>
<head>
    {% if check %}
    <form method="GET">
        <input name="x" id="x1" placeholder="Enter a subject" value = {{ last_result.result }} />
        <input name="y" id="y1" placeholder="Enter a subject" />
        <li><input name="operate_list" type="checkbox" value="+"><label>+</label></li>
        <li><input name="operate_list" type="checkbox" value="-"><label>-</label></li>
        <li><input name="operate_list" type="checkbox" value="*"><label>*</label></li>
        <li><input name="operate_list" type="checkbox" value="/"><label>/</label></li>
        <li><input name="find value" type="submit" value="result"></li>
         <li><input name="continue"type="submit" value="continue"></li>
        {% csrf_token %}
    </form>
       {% for key,value in result_list.items %}
        <p>the result {{ x }} {{ key }} {{ y }} is :{{ value }}</p></td>
    {% endfor %}

    <h1 name = 'history'>History</h1>
    {% for history in history %}
        <p>the result {{ history }}</p></td>
    {% endfor %}
    <form method="GET">
        <input name="clear_history" type="submit" value="Clear History">
        {% csrf_token %}
    </form>
    <a href="{% url 'calculate:home' %}">go to post method</a>
    <a href="{% url 'calculate:about' %}">go to About</a>
    {% else %}
    <form method="GET">
        <input name="x" id="x" placeholder="Enter a subject" />
        <input name="y" id="y" placeholder="Enter a subject" />
        <li><input name="operate_list" type="checkbox" value="+"><label>+</label></li>
        <li><input name="operate_list" type="checkbox" value="-"><label>-</label></li>
        <li><input name="operate_list" type="checkbox" value="*"><label>*</label></li>
        <li><input name="operate_list" type="checkbox" value="/"><label>/</label></li>
        <li><input name="find value" type="submit" value="result"></li>
         <li><input name="continue"type="submit" value="continue"></li>
        {% csrf_token %}
    </form>
       {% for key,value in result_list.items %}
        <p>the result {{ x }} {{ key }} {{ y }} is :{{ value }}</p></td>
    {% endfor %}

    <h1 name = 'history'>History</h1>
    {% for history in history %}
        <p>the result {{ history }}</p></td>
    {% endfor %}
    <form method="GET">
        <input name="clear_history" type="submit" value="Clear History">
        {% csrf_token %}
    </form>
    <a href="{% url 'calculate:home' %}">go to post method</a>
    <a href="{% url 'calculate:about' %}">go to About</a>
    {% endif %}
</head>
<body>

</body>
</html>